volumes:
  pgdata:
  pgdata-test:

services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FROM=${FROM}
      - TO=${TO}
    working_dir: /app
    volumes:
      - ./token.json:/app/token.json
      - ./credentials.json:/app/credentials.json

  database:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notify-stock
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - 5555:5432

  database-test:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notify-stock
    volumes:
      - pgdata-test:/var/lib/postgresql
    ports:
      - 5556:5432
