// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notifystock

import (
	"context"
)

// Injectors from wire.go:

func InitStockRegister(dsn string, client HTTPClientInterface) *StockRegister {
	financeClient := NewFinanceClient(client)
	db := NewDB(dsn)
	stockRepository := NewStockRepository(db)
	stockRegister := NewStockRegister(financeClient, stockRepository)
	return stockRegister
}

func InitStockNotifier(ctx context.Context, credentialsPath string, client HTTPClientInterface) (*StockNotifier, error) {
	financeClient := NewFinanceClient(client)
	gmailService, err := GmailServiceFactory(ctx, credentialsPath)
	if err != nil {
		return nil, err
	}
	stockNotifier := NewStockNotifier(financeClient, gmailService)
	return stockNotifier, nil
}

func InitStockRepository(dsn string) *StockRepository {
	db := NewDB(dsn)
	stockRepository := NewStockRepository(db)
	return stockRepository
}
