// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package graph

import (
	"github.com/heyjun3/notify-stock/internal"
)

// Injectors from wire.go:

func InitResolver(dsn string) *Resolver {
	stockRepository := notifystock.InitStockRepository(dsn)
	notificationRepository := notifystock.InitNotificationRepository(dsn)
	notificationCreator := notifystock.NewNotificationCreator(notificationRepository)
	resolver := NewResolver(stockRepository, notificationRepository, notificationCreator)
	return resolver
}
