// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package graph

import (
	"github.com/heyjun3/notify-stock/internal"
	"log/slog"
)

// Injectors from wire.go:

func InitResolver(dsn string) *Resolver {
	stockRepository := notifystock.InitStockRepository(dsn)
	symbolFetcher := notifystock.InitSymbolFetcher(dsn)
	notificationRepository := notifystock.InitNotificationRepository(dsn)
	notificationCreator := notifystock.NewNotificationCreator(notificationRepository)
	notificationFetcher := notifystock.NewNotificationFetcher(notificationRepository)
	resolver := NewResolver(stockRepository, symbolFetcher, notificationCreator, notificationFetcher)
	return resolver
}

func InitRootDirective(logger *slog.Logger) *DirectiveRoot {
	directive := NewAuthDirective(logger)
	directiveRoot := NewDirectiveRoot(directive)
	return directiveRoot
}
