// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Mutation struct {
}

type Notification struct {
	ID     string    `json:"id"`
	Symbol string    `json:"symbol"`
	Email  string    `json:"email"`
	Time   time.Time `json:"time"`
}

type NotificationInput struct {
	Symbol string    `json:"symbol"`
	Email  string    `json:"email"`
	Time   time.Time `json:"time"`
}

type Query struct {
}

type Stock struct {
	Symbol    string    `json:"symbol"`
	Timestamp time.Time `json:"timestamp"`
	Close     float64   `json:"close"`
}

type Symbol struct {
	Symbol       string `json:"symbol"`
	CurrentStock *Stock `json:"currentStock"`
}

type SymbolInput struct {
	Symbol string `json:"symbol"`
}
