// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ChartInput struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

type Mutation struct {
}

type Notification struct {
	ID     string    `json:"id"`
	Symbol string    `json:"symbol"`
	Email  string    `json:"email"`
	Time   time.Time `json:"time"`
}

type NotificationInput struct {
	Symbol string    `json:"symbol"`
	Email  string    `json:"email"`
	Time   time.Time `json:"time"`
}

type Query struct {
}

type Stock struct {
	Symbol    string    `json:"symbol"`
	Timestamp time.Time `json:"timestamp"`
	Close     float64   `json:"close"`
}

type Symbol struct {
	Symbol       string        `json:"symbol"`
	CurrentStock *Stock        `json:"currentStock"`
	Detail       *SymbolDetail `json:"detail"`
	Chart        []*Stock      `json:"chart,omitempty"`
}

type SymbolDetail struct {
	Symbol         string  `json:"symbol"`
	ShortName      string  `json:"shortName"`
	LongName       string  `json:"longName"`
	Price          float64 `json:"price"`
	Change         string  `json:"change"`
	ChangePercent  string  `json:"changePercent"`
	Volume         *string `json:"volume,omitempty"`
	MarketCap      *string `json:"marketCap,omitempty"`
	CurrencySymbol string  `json:"currencySymbol"`
}

type SymbolInput struct {
	Symbol string `json:"symbol"`
}
