// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type ChartInput struct {
	Symbol *string   `json:"symbol,omitempty"`
	Start  time.Time `json:"start"`
	End    time.Time `json:"end"`
}

type Mutation struct {
}

type Notification struct {
	ID     string    `json:"id"`
	Symbol string    `json:"symbol"`
	Email  string    `json:"email"`
	Time   time.Time `json:"time"`
}

type NotificationInput struct {
	Symbol string    `json:"symbol"`
	Email  string    `json:"email"`
	Time   time.Time `json:"time"`
}

type Query struct {
}

type Stock struct {
	Symbol    string  `json:"symbol"`
	Timestamp string  `json:"timestamp"`
	Price     float64 `json:"price"`
}

type Symbol struct {
	Symbol string        `json:"symbol"`
	ID     string        `json:"id"`
	Detail *SymbolDetail `json:"detail"`
	Chart  []*Stock      `json:"chart"`
}

type SymbolDetail struct {
	Symbol         string  `json:"symbol"`
	ShortName      string  `json:"shortName"`
	LongName       string  `json:"longName"`
	Price          float64 `json:"price"`
	Change         string  `json:"change"`
	ChangePercent  string  `json:"changePercent"`
	Volume         *string `json:"volume,omitempty"`
	MarketCap      *string `json:"marketCap,omitempty"`
	CurrencySymbol string  `json:"currencySymbol"`
}

type SymbolInput struct {
	Symbol string `json:"symbol"`
}
