mutation createNotification($createNotificationInput: NotificationInput!) {
  createNotification(input: $createNotificationInput) {
    id
    hour
    targets {
      id
      symbol
      shortName
    }
  }
}
