query GetSymbols($chartInput: ChartInput!) {
  symbols {
    id
    symbol
    detail {
      symbol
      shortName
      longName
      price
      change
      changePercent
      volume
      marketCap
      currencySymbol
    }
    chart(input: $chartInput) {
      symbol
      timestamp
      price
    }
  }
}
