// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package notifystock

import (
	"context"
)

// Injectors from wire.go:

func InitStockRegister(dsn string, client HTTPClientInterface) *StockRegister {
	financeClient := NewFinanceClient(client)
	db := NewDB(dsn)
	stockRepository := NewStockRepository(db)
	stockRegister := NewStockRegister(financeClient, stockRepository)
	return stockRegister
}

func InitStockNotifier(ctx context.Context, token string, client HTTPClientInterface) (*StockNotifier, error) {
	financeClient := NewFinanceClient(client)
	emailClient := NewEmailClient(token)
	stockNotifier := NewStockNotifier(financeClient, emailClient)
	return stockNotifier, nil
}

func InitStockRepository(dsn string) *StockRepository {
	db := NewDB(dsn)
	stockRepository := NewStockRepository(db)
	return stockRepository
}
