volumes:
  pgdata:
  pgdata-test:

services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FROM=${FROM}
      - TO=${TO}
      - MAIL_TOKEN=${MAIL_TOKEN}
      - DBDSN=postgres://${DB_USER}:${DB_PASSWORD}@database:5432/notify-stock?sslmode=disable
    working_dir: /app

  database:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notify-stock
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5555:5432
