volumes:
  pgdata:
  pgdata-test:

services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FROM=${FROM}
      - TO=${TO}
      - MAIL_TOKEN=${MAIL_TOKEN}
      - DBDSN=postgres://${DB_USER}:${DB_PASSWORD}@database:5432/notify-stock?sslmode=disable
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECT_URL=${OAUTH_REDIRECT_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    working_dir: /app
    command: ["server"]
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notify-stock
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5555:5432
