networks:
  default:
    name: api_default
    external: true

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    environment:
      - PORT=${PORT:-8080}
    ports:
      - 80:${PORT:-8080}
